# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
# la build verra eseguiota all'interno di um docker container
version: 2
jobs:
    build:
        docker:
        # specify the version you desire here
        - image: circleci/openjdk:11-browsers-legacy

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/postgres:9.4

        working_directory: ~/repo

        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

        steps:
        - checkout

        # Download and cache dependencies
        # CircleCI ha la capacita di memorizzare
        # in una cache le dipendenze
        - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "pom.xml" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

        - run: mvn install -DskipTests

        #mvn dipendenze offline dice di andare
        #andare a prendere tutte le dipendenze
        - run: mvn dependency:go-offline

        # Possiamo salvare la cache
        #e avere l'elenco delle dipendenze in  modo relativo
        - save_cache:
              paths:
              - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}

        # run tests!
        # eseguo i test d'integrazione e quelli unitari
        # questo comando puo' essere personalizzato
        # per progetti semplici e' piu' che sufficiente
        - run: mvn integration-test
