# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
# la build verra eseguiota all'interno di um docker container
version: 2
jobs:
    build:
        docker:
        # specify the version you desire here
        # Oltre a qui Modifica da 11 a 1.8
        # 1- nei file pom.xml
        # 2- Sotto Project Structure / Project
        # 3- Sotto Project Structure / Modules
        # 4- Settings / Build / Compile / Java Compiler/ByteCode Tab
        - image: circleci/openjdk:11-browsers-legacy
        #- image: circleci/openjdk:1.8-browsers-legacy

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/postgres:9.4

        working_directory: ~/repo

        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

        steps:
        - checkout

        # Download and cache dependencies
        # CircleCI ha la capacita di memorizzare
        # in una cache le dipendenze
        # Ripristina la cache dal checksum sul pom
        - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "pom.xml" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

        # Modifica per non dare errore su Circle
        # Necessita di piu' passaggi prima solo la build
        # saltando i test
        # Installazione di esecuzione che installa
        # i moduli nella cache Maven
        # ma salta i test che saranno eseguiti in fondo
        # Il tutto è dovuto al fatto di avere 2 moduli
        # in cui il modulo web ha bisogno del modulo data
        # ma maven di default non guarda il nostro codice
        # ma guarda soltanto il contenuto della cache maven .m2
        #- run: mvn generate-resources
        - run: mvn install -DskipTests

        #mvn dipendenze offline dice di andare
        #andare a prendere tutte le dipendenze
        # a volte dopo la modifica puo non funzionare
        # lo stesso probabilmente perche' si va offline
        - run: mvn dependency:go-offline

        # Possiamo salvare la cache
        #e avere l'elenco delle dipendenze in  modo relativo
        # .m2 e la directory locale dove contenere la cache
        - save_cache:
              paths:
              - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}

        # run tests!
        # eseguo i test d'integrazione e quelli unitari
        # questo comando puo' essere personalizzato
        # per progetti semplici e' piu' che sufficiente
        # Da verificare con java8 essendo un progetto
        # Multi Modulo potrebbe servire installare maven sotto la cache
        # quindi in caso di errori modificare la seguente riga
        # run: mvn install (forse basta skip test fatto sopra sopra)
        # - run: mvn install
        - run: mvn integration-test
